### ISSUE TITLE
Add to biopam/bioconda

### ISSUE THREAD

**Issue by ihodes** [hammerlab/hlarp#2]
Would be nice to use the biopam infrastructure in Biokepi to get this in!

**Comment by rleonid** [comment]
No, opam is better suited for projects in OCaml.

I am reticent to push tools that have such a unique utility into the public domain/repositories. My current preference would be bioconda, but for biokepi purposes I think we should maintain our own repo. Whether it should be `opam` or `conda` based is an open question; how many forks and of what projects does the lab want to maintain.

**Comment by ihodes** [comment]
Pushed to `opam` to get going on this for now.
