### ISSUE TITLE
Clarify pronunciation of hlarp

### ISSUE THREAD

**Issue by ihodes** [hammerlab/hlarp#7]

**Comment by rleonid** [comment]
Kind of like "larp" but with a light "h" sound.

Seriously though, if you have a better name...

**Comment by ihodes** [comment]
I love it.

**Comment by rleonid** [comment]
Maybe we should just call it `hlatools` ?

**Comment by arahuja** [comment]
Can we pronounce it h'`latools`, soft h

**Comment by ihodes** [comment]
I like the Lovecraftian direction we're going.

**Comment by rleonid** [comment]
I was trying to draw a reference to 'harp' 's ... just noticed that [HlaTools](https://github.com/bnbowman/HlaTools) is taken.
